version: "3"
services:
    feedback-service-api:
        build: feedback-service/src/Api
        ports:
            - "5001:80"
        depends_on:
            - db
            - event-service-api
    event-service-api:
        build: event-service/src/Api
        ports:
            - "5000:80"
        depends_on:
            - db
            - event-service-migration
    event-service-migration:
        build: "event-service/src/Database"
        depends_on: 
            - db
    db:
        image: "microsoft/mssql-server-linux"
        volumes:
            - mssqldata:/var/lib/mssql
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Qwer1234*"
            ACCEPT_EULA: "Y"

volumes:
    mssqldata: